/**
 * Privacy Policy — dedicated route.
 *
 * Covers actual Webloom platform behaviour. Unverifiable legal facts are
 * clearly marked as `TODO` placeholders — nothing is invented.
 *
 * TODO(owner): Have a legal professional review before public launch.
 */
import usePageMetadata from '../hooks/usePageMetadata';
import { routes, siteConfig } from '../config/site';

const accent = 'text-webloom-accent';
const strong = 'font-medium text-webloom-text';

export default function PrivacyPolicy() {
  usePageMetadata(routes.PRIVACY);

  return (
    <article className="mx-auto max-w-3xl pb-20">
      <header className="mb-10">
        <p className="text-[11px] uppercase tracking-[0.18em] text-webloom-dim">Legal</p>
        <h1 className="mt-3 text-3xl font-semibold tracking-tight text-webloom-text">Privacy Policy</h1>
        <p className="mt-3 text-sm text-webloom-muted">Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
      </header>

      <div className="space-y-8 text-[15px] leading-[1.8] text-webloom-muted">
        <Section title="1. Who we are">
          <p>
            Webloom (<span className={strong}>{siteConfig.legal.companyName}</span>) provides an AI-powered web intelligence and structured business extraction platform.
          </p>
          <p className="mt-2">
            Contact: <a className={accent} href={`mailto:${siteConfig.contact.email}`}>{siteConfig.contact.email}</a>
          </p>
          <p className="mt-2">
            Address: <span className="text-webloom-warning font-medium">{typeof siteConfig.contact.address === 'string' ? siteConfig.contact.address : siteConfig.contact.address.line1 || 'TODO: provide registered address'}</span>
          </p>
        </Section>

        <Section title="2. Information we collect">
          <p>Webloom may collect:</p>
          <ul className="mt-3 list-disc space-y-2 pl-5">
            <li><span className={strong}>Account and contact information</span> — email, business name, and any details submitted through forms.</li>
            <li><span className={strong}>Source URLs</span> — Google Maps URLs and related pages submitted for analysis.</li>
            <li><span className={strong}>Extraction results</span> — structured business data generated by the platform from submitted sources.</li>
            <li><span className={strong}>Usage data</span> — page views, feature interactions, and diagnostic logs required to operate the service.</li>
            <li><span className={strong}>Cookies and local storage</span> — strictly necessary session storage; non-essential analytics only if consent is granted.</li>
          </ul>
        </Section>

        <Section title="3. AI processing">
          <p>
            Webloom uses AI models to extract, normalise, infer, and enrich business information from submitted sources.
            AI-generated outputs are <span className={strong}>labelled as AI-generated or AI-inferred</span> in internal provenance metadata and are not treated as independently verified provider data.
          </p>
        </Section>

        <Section title="4. How we use your information">
          <ul className="list-disc space-y-2 pl-5">
            <li>To provide and operate the Webloom platform.</li>
            <li>To extract and normalise structured business intelligence.</li>
            <li>To improve extraction quality, reliability, and performance.</li>
            <li>To respond to support requests.</li>
            <li>To maintain platform security and prevent abuse.</li>
          </ul>
        </Section>

        <Section title="5. Third-party providers">
          <p>
            Webloom may interact with third-party providers such as mapping/data providers, hosting infrastructure, and AI model gateways.
            These providers process data only as necessary to deliver their functionality.
          </p>
        </Section>

        <Section title="6. Data retention">
          <p>
            Business analyses, extracted profiles, and source-cache records are retained to support recurring analyses and reliability.
            <span className="text-webloom-warning font-medium ml-1">TODO: define your official retention periods and deletion policy before launch.</span>
          </p>
        </Section>

        <Section title="7. Data security">
          <p>
            Webloom uses industry-standard transport security, environment separation, and least-privilege access controls.
            No system is perfectly secure; you should contact us immediately if you believe your data has been compromised.
          </p>
        </Section>

        <Section title="8. Your rights">
          <p>
            Depending on your jurisdiction, you may have rights to access, correct, delete, or port your personal information.
            Please contact <a className={accent} href={`mailto:${siteConfig.contact.email}`}>{siteConfig.contact.email}</a>.
          </p>
        </Section>

        <Section title="9. Changes to this policy">
          <p>We may update this policy when platform behaviour, providers, or legal requirements change.</p>
        </Section>
      </div>
    </article>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-xl font-semibold tracking-tight text-webloom-text">{title}</h2>
      <div className="mt-3">{children}</div>
    </section>
  );
}